M48
; DRILL file KiCad 10.0.5 date 2026-08-17T13:20:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-17T13:20:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,MixedPlating,1,4
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.600
%
G90
G05
T1
X5.0Y-46.0
X7.0Y-46.0
X9.0Y-46.0
X10.0Y-6.0
X11.0Y-46.0
X12.0Y-6.0
X14.0Y-6.0
T2
X81.0Y-16.0
X81.0Y-39.0
T3
X78.46Y-13.46
X78.46Y-36.46
X83.54Y-13.46
X83.54Y-36.46
M30
